# https://github.com/jeffreytse/jekyll-theme-yat/?tab=readme-ov-file#remote-theme-method-with-github-pages
remote_theme: "jeffreytse/jekyll-theme-yat"

# https://github.com/jeffreytse/jekyll-theme-yat/blob/master/_config.yml
title: Title
email: ohno.github@gmail.com
author: Shuhei Ohno
copyright: "© 2023-{currentYear} {author}"
description: "description description description description description description description description description description"

home:
  heading: "HEADING HEADING HEADING"
  subheading: "subheading subheading subheading"
  banner: "#95C8BF"

night_mode: "manual"
favicon: "./favicon.svg"